### ISSUE TITLE
This isn't for the password manager but....

### ISSUE THREAD

**Issue by Craftzman7** [Azusa-chxn/APassword-Manager#11]
Is Neko-Chxn api gone? And if so why?

**Comment by Azusa-chxn** [comment]
This was due to server costs. The service was out of private pocket for more than a year.  Since the prices at the hoster have risen (domain 20€ a year and server every 3 months 42€) and through Corona my income is half gone I could no longer pay the server (bc cheaper server has caused an overlord). The closure of the API and Neko-chxn was announced 1 month before it was over. 

Since I still have Neko-chxn completely local I will rewrite the API soon which will hopefully improve the image loading time. If you are interested in helping or just want an update my Discord: ꋊꄲꋊꏂ#0001
